### ISSUE TITLE
Naming Schema for multiple PDU

### ISSUE THREAD

**Issue by andrewt81** [mtdcr/homeassistant-aten-pe#2]
I own multiple PDUs

Currently the naming schema for entities is something like this:

switch.outlet_1

If i add a second or more pdus entities for same outlet (it's the same for other readings available from pdus) are named
switch.outlet_1-2
switch.outlet_1-3
and so on.. 

It's very very confusing

**Comment by mtdcr** [comment]
I feel your pain, but currently I don't intend to invest a substantial amount of time in this area. I'd happily accept contributions, but care should be taken not to break existing setups.

However, PDUs appear as devices to Home Assistant, listing all their entities under `/config/devices/device/<ID>`. You can give names to entities or even rename entity IDs from there.

By default, names for outlets set up in the PDU's management interface are used as entity names. "Outled <nr>" is just a fallback for unconfigured devices.

**Comment by andrewt81** [comment]
If you give a nane to the PDU in http panel then the PDU Is named the same also in Home Assistant.

Problem solved :)
