### ISSUE TITLE
Aten Integration fales to install with 2024.3 HA

### ISSUE THREAD

**Issue by burtonpark** [mtdcr/homeassistant-aten-pe#3]
Hi your Aten integration fails to install on lastest home assistant, could you take a look at it, 
many thanks
Logger: homeassistant.util.package
Source: util/package.py:122
First occurred: 12:18:41 (3 occurrences)
Last logged: 12:18:45

Unable to install package atenpdu==0.6.1: ERROR: Cannot install atenpdu==0.6.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by ffish77** [comment]
+1

**Comment by mtdcr** [comment]
Should get fixed with atenpdu 0.6.2 soon.

**Comment by mtdcr** [comment]
You can try to update now.

**Comment by ffish77** [comment]
Thank you, solved!
